#!/bin/bash
/config/scripts/openvpnas --pidfile=/config/pid/openvpn.pid --logfile=/config/log/openvpn.log
exec tail -F -q --pid=$(cat /config/pid/openvpn.pid) $(ls -t /config/log/openvpn.log | head -n 2)

