#!/usr/bin/with-contenv bash

# make folders
mkdir -p /openvpn{/pid,/sock,/tmp}  /config/log /config/etc/tmp

# copy config
[[ ! -f /config/bin/ovpn-init ]] && \
	cp -pr /usr/local/openvpn_as/* /config/

# clear old pid and sock files
for file in /openvpn/sock/*
	do
		if [ -e "$file" ]; then
		rm -rf "$file"
		fi
	done

for file in /openvpn/pid/*
	do
		if [ -e "$file" ]; then
		rm -rf "$file"
		fi
	done


# permissions
chown abc:abc /config/log /config/etc/tmp
chmod -R 755 /openvpn
