#!/usr/bin/with-contenv bash

# make folders
mkdir -p /openvpn{/pid,/sock,/tmp} /dev/net /config/log /config/etc/tmp

# create tun device
if [ ! -c /dev/net/tun ]; then
  mknod /dev/net/tun c 10 200
fi

shopt -s extglob
# install or update openvpn-as
if [ -f /openvpn/openvpn.deb ]; then
	rm -rf /usr/local/openvpn_as
	ln -s /config /usr/local/openvpn_as
	if [ ! -f /config/etc/as.conf ]; then
		echo "installing openvpn-as for the first time"
		dpkg -i /openvpn/openvpn-clients.deb
		dpkg -i /openvpn/openvpn.deb
		echo "Stopping openvpn-as now; will start again later after configuring"
		kill `cat /var/run/openvpnas.pid`
		rm /openvpn/openvpn.deb
		sed -i \
			-e 's#=openvpn_as#=abc#g' \
			-e 's#~/tmp#/openvpn/tmp#g' \
			-e 's#~/sock#/openvpn/sock#g' \
			/usr/local/openvpn_as/etc/as_templ.conf
	else
		echo "existing data found, reinstalling openvpn-as"
		mkdir -p /config/backup
		cd /config/etc/db || exit
		DBFILESBAK="*.db"
		for f in $DBFILESBAK
		do
			echo "backing up $f"
			sqlite3 "$f" .dump > /config/backup/"$f"
		done
		echo "backing up as.conf"
		cp /config/etc/as.conf /config/backup/as.conf
		cd /config || exit
		rm -rf !("backup"|"log")
		dpkg -i /openvpn/openvpn-clients.deb
		dpkg -i /openvpn/openvpn.deb
		echo "Stopping openvpn-as now; will start again later after configuring"
		kill `cat /var/run/openvpnas.pid`
		rm /openvpn/openvpn.deb
		sed -i \
			-e 's#=openvpn_as#=abc#g' \
			-e 's#~/tmp#/openvpn/tmp#g' \
			-e 's#~/sock#/openvpn/sock#g' \
			/usr/local/openvpn_as/etc/as_templ.conf
	fi
fi
shopt -u extglob

# clear old sock files
for file in /openvpn/sock/*
	do
		if [ -e "$file" ]; then
		rm -rf "$file"
		fi
	done

# clear old pid files
for file in /openvpn/pid/*
	do
		if [ -e "$file" ]; then
		rm -rf "$file"
		fi
	done


# permissions
chown abc:abc /config/log /config/etc/tmp
chmod -R 755 /openvpn
